esphome:
  name: led-controller-1
  friendly_name: LED-Controller-1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "A7/yPVQlZ8iXmnI/Zw1jFkoAKNDb9RMuOr4dR6iZ16s="

ota:
  - platform: esphome
    password: "8606e0b37cf4fdab65869aad6e50621a"

wifi:
  ssid: !secret wifi_ssid_m
  password: !secret wifi_password_m

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Controller-1"
    password: "c7TExWdd6VRP"

light:
  - platform: monochromatic
    name: "Light Bar"
    output: gpio_light
    id: light_bar1

    icon: "mdi:ceiling-light"



output:
  - platform: ledc
    pin: GPIO10
    id: gpio_light
    inverted: true

captive_portal:
